id: I03524BE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:03:06+00:00'
last_modified: '2022-06-07T21:14:52.158173+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12667
  title: ཆོས་སྤྱོད་ཐོར་བུ། ༼ནམ་མཁའ་ཁྱུང་རྫོང་གི་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    94CD:
      image_group_id: I1KG12797
      title: ''
      total_pages: 482
      order: 1
      base_file: 94CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
